### ISSUE TITLE
Allow dictionary() to be initialized

### ISSUE THREAD

**Issue by jsergiu** [Freeyayo/ifoo#10]
dictionary() should accept an array or an object as the first argument for initialization.

**Comment by Freeyayo** [comment]
that's great. Dictionary in c# should have initial operation.

btw, if we could add `private` while we're declaring some private properties?

![image](https://user-images.githubusercontent.com/29268642/86377771-5473c180-bcbb-11ea-8309-a2c5f699a7cf.png)

**Comment by Freeyayo** [comment]
> that's great. Dictionary in c# should have initial operation.
> 
> btw, if it's better adding `private` while we're declaring some private properties?
> 
> ![image](https://user-images.githubusercontent.com/29268642/86377771-5473c180-bcbb-11ea-8309-a2c5f699a7cf.png)

This issue has been fixed and merge to `dev` and `master` branch

**Comment by jsergiu** [comment]
I think this can be closed since it was implemented in #19 . I also declared the members as private.
