### ISSUE TITLE
Missing return type on dictionary

### ISSUE THREAD

**Issue by Freeyayo** [Freeyayo/ifoo#11]
Missing return type on dictionary:

![image](https://user-images.githubusercontent.com/29268642/86476461-2b196b00-bd79-11ea-9779-fe8b13e762ed.png)

@jsergiu

**Comment by Freeyayo** [comment]
I didn't fix it, just show a difference

**Comment by Freeyayo** [comment]
There's another problem I found(not your problem):

Your code 👇
![image](https://user-images.githubusercontent.com/29268642/86488549-ecdd7500-bd93-11ea-8036-d276e23c99b2.png)

But I need to do that this way 👇, then testing can be done on my computer, otherwise it won't pass the test
![image](https://user-images.githubusercontent.com/29268642/86488525-dd5e2c00-bd93-11ea-8539-bd37c1ca81c8.png)

Error messages:
![image](https://user-images.githubusercontent.com/29268642/86488987-73468680-bd95-11ea-9e90-3fe032fc9068.png)

If you know why please tell me and `dictionary` is really cool feature, looking forward it's new methods 😄

**Comment by Freeyayo** [comment]
And ... I won't change your code.

**Comment by jsergiu** [comment]
These should also be fixed by #16 but let me know if there are any other issues.
