### ISSUE TITLE
Bug on `dictionary`

### ISSUE THREAD

**Issue by Freeyayo** [Freeyayo/ifoo#14]
This is a cool implementation,  we can use this in some situations

But there's a bug, hope can be fixed in the future version, thanks

![image](https://user-images.githubusercontent.com/29268642/86493978-2d45ee80-bda6-11ea-9149-5ae498ee809d.png)

Q:
If it's better that use `Object.create(null)` to create dictionary?
Because we may want a cleaner and a new data structure.

**Comment by jsergiu** [comment]
https://github.com/Freeyayo/ifoo/pull/16 should fix it
