### ISSUE TITLE
Return a safe object when pass string to deserialize

### ISSUE THREAD

**Issue by Freeyayo** [Freeyayo/ifoo#5]
![image](https://user-images.githubusercontent.com/29268642/86155171-a0492e00-bb36-11ea-82f8-f5fa466c19cc.png)

@jsergiu 
Return an object but it's val shouldn't be NaN.
A safe return object cannot interrupt program

**Comment by jsergiu** [comment]
The function should throw an error in this case so the user can catch the error. Otherwise he would have to check if val is Nan or if the returned object (tree) is valid.

**Comment by Freeyayo** [comment]
Right, and I'll fix it in the next version

```js
// example:
// valid input expected:
const serializedTree = "[1,2,3,4,null,5]";
deserialize(serializedTree)
```
I may use regular expression to match valid input, if the input is invalid, an error should be thrown.

I'll keep this issue opening until it is fixed.
