### ISSUE TITLE
Type bug

### ISSUE THREAD

**Issue by Freeyayo** [Freeyayo/ifoo#8]
![image](https://user-images.githubusercontent.com/29268642/86265719-b7e7eb80-bbf6-11ea-948e-4c9237e42dfa.png)

```js
- entries(): string[];
+ entries(): KeyValue;
```

Hi , @jsergiu 
I think it may be a bug and fixed it properly
If I was wrong, recover it please

**Comment by jsergiu** [comment]
Hi. It is a bug but the return type should actually be KeyValue[], because entries() returns an array of key-value pairs. I will fix it.

**Comment by Freeyayo** [comment]
thx
